name = "cfworkers-ld"
main = "worker/script.js"
compatibility_date = "2022-10-17"

account_id = "90e01918bfda495b428c123285831fff"

kv_namespaces = [
   {binding = "MY_KV", id="daa0afa00af34c71b752f96d3330f815", preview_id="f9ea6aae479b4b56bab386f1e30acaa9"},
]

[site]
bucket = "./public"

[build]
command = "npm run build"
