account_id = "62c78308ac5d6ac35b1c395a4fc5abc8"
name = "cfworkers-ld"
type = "webpack"
webpack_config = "webpack.config.js"
workers_dev = true
kv_namespaces = [
  { binding = "MY_KV", preview_id = "e88af073edb14c929600e62218359bfd", id = "ffc9417d31f54731be4a6fd77aa795cc" },
  { binding = "SITE_ASSETS", preview_id = "43ecd3c7d05f45caa947fb48fd7b7c83", id = "a0a8f76d2fe14947826adc1453c2e90c" },
]
site = { bucket = "./public" }
compatibility_date = "2021-12-13"
