name = "example"
main = "dist/index.mjs"
compatibility_date = "2021-11-03"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [{ binding = "LD_KV", id = "YOUR_KV_ID", preview_id = "YOUR_PREVIEW_KV_ID" }]

[build]
command = "node build.js"
